---

#
#  Trick #1 - dynamic sleep duration
#  
#  Since startup, wifi, sensor, and HA sync take anywhere from 2 seconds to 12.
#  So to achieve a 60s or 600s loop we dynamically adjust how long to sleep
#
globals:
  # - id: delay_int
    # type: int
    # restore_value: no
    # initial_value: '99999'
  - id: mqtt_done_switch
    type: bool
    restore_value: no
    initial_value: 'false'
  - id: mqtt_done_sleep_interval
    type: bool
    restore_value: no
    initial_value: 'false'

esphome:
  name: ${dev_name}
  friendly_name: ${dev_friendly_name}
  
  on_boot:
    - priority: 600
      then: 
        - output.turn_on: debug_gpio
        - logger.log: "debug_gpio turned ON"

    # - priority: 199
      # then:
        # - logger.log: "on_boot: consider_deep_sleep..."
        # - script.execute: consider_deep_sleep

# # To remove ota password...
# # Must put password in .base.yaml ota: section
  # on_boot:
    # - lambda: |-
        # id(ota_id).set_auth_password("");

esp32:
  board: dfrobot_beetle_esp32c3
  variant: esp32c3
  framework:
    type: arduino

# binary_sensor:

mqtt:
  broker: 192.168.1.200
  username: !secret mqtt_user
  password: !secret mqtt_password
  discovery: false
  # birth_message:
    # topic: ${dev_name}/status/availability
    # payload: online
  # will_message:
    # topic: ${dev_name}/status/availability
    # payload: offline
  on_message:
  - topic: candles/switch
    payload: 'ON'
    then:
      # - switch.turn_on: switch1
      - light.turn_on:
          id: rgbw_led
          color_mode: RGB_WHITE
          brightness: 100%
          red: 100%
          green: 50%
          blue: 0%
          white: 70%
          # effect: "Custom Flicker"
      - globals.set:
          id: mqtt_done_switch
          value: 'true'
      - logger.log: "switch1 ON: consider_deep_sleep"
      - script.execute: consider_deep_sleep
  - topic: candles/switch
    payload: 'OFF'
    then:
      # - switch.turn_off: switch1
      - light.turn_off:
          id: rgbw_led
      - globals.set:
          id: mqtt_done_switch
          value: 'true'
      - logger.log: "switch1 OFF: consider_deep_sleep"
      - script.execute: consider_deep_sleep

light:
  - platform: monochromatic
    output: blue_led_pwm
    id: blue_led_light
    name: "Blue LED"
    restore_mode: ALWAYS_ON
    # internal: true
    disabled_by_default: true
    effects:
      - pulse:
      - pulse:
          name: "Custom Pulse"
          transition_length: 1.5s
          update_interval: 1.5s
          min_brightness: 10%
          max_brightness: 85%
    on_turn_on:
      then:
        - light.turn_on:
            id: blue_led_light
            effect: "Custom Pulse"

  - platform: neopixelbus
    id: rgbw_led
    name: "Candle"
    icon: mdi:candle
    type: GRBW
    variant: SK6812
    pin: GPIO21
    num_leds: 1
    default_transition_length: 0s
    # internal: true
    disabled_by_default: true
    restore_mode: RESTORE_DEFAULT_OFF
    # color_correct: [100%, 100%, 100%, 100%]
    # color_correct: [1%, 0%, 0%, 10%]
    effects:
      - flicker:
      - flicker:
          name: "Custom Flicker"
          alpha: 95%
          intensity: 5%
          # update_interval: 250ms

# for PWM status led:
output:
  - platform: ledc
    id: blue_led_pwm
    pin: GPIO8
    inverted: true
    min_power: 0%
    max_power: 100%

  - platform: gpio
    pin: GPIO10
    id: debug_gpio

# switch:
  # - platform: template
    # id: switch1
    # optimistic: true
    # # internal: true
    # disabled_by_default: true
    # turn_on_action:
      # - light.turn_on:
          # id: rgbw_led
          # color_mode: RGB_WHITE
          # brightness: 100%
          # red: 100%
          # green: 50%
          # blue: 0%
          # white: 70%
          # # effect: "Custom Flicker"
    # turn_off_action:
      # - light.turn_off:
          # id: rgbw_led
    # restore_mode: RESTORE_DEFAULT_OFF

sensor:
  - platform: adc
    pin: GPIO3
    name: "Battery Voltage"
    update_interval: 60s
    attenuation: 12db
    disabled_by_default: true
    entity_category: diagnostic

  - platform: uptime
    name: "Uptime seconds"
    id: uptime_sec
    update_interval: 60s
    disabled_by_default: true
    entity_category: diagnostic
    
  - platform: wifi_signal
    name: "WiFi RSSI"
    id: wifi_rssi
    update_interval: 60s
    disabled_by_default: true
    entity_category: diagnostic
    
  - platform: template
    name: "Wakeup Cause"
    accuracy_decimals: 0
    lambda: return esp_sleep_get_wakeup_cause();
    disabled_by_default: true
    entity_category: diagnostic

deep_sleep:
  id: deep_sleep1

interval:
  - interval: 1.2s
    then:
      - logger.log: "interval: consider_deep_sleep"
      - script.execute: consider_deep_sleep

script:
  - id: consider_deep_sleep
    mode: queued
    then:
      - logger.log: "Running consider_deep_sleep..."
      - if:
          # path 1, we dont have connection to HA yet, so just chill for a bit
          condition:
            - lambda: |-
                ESP_LOGD("stefan", "mqtt_done_switch: %d  mqtt_done_sleep_interval: %d", id(mqtt_done_switch), id(mqtt_done_sleep_interval) );
                return (id(mqtt_done_switch) && id(mqtt_done_sleep_interval));
          then:
            - lambda: |-
                static uint sleep_dur=0;
                if ( strncmp( id(sleep_interval).state.c_str(), "always on", 9) == 0 ) {
                  id(deep_sleep1).prevent_deep_sleep();
                  ESP_LOGD("stefan", "sleep_interval is always on (for OTA)");
                }
                else {
                  if ( strcmp( id(sleep_interval).state.c_str(), "60min") == 0 ) {
                    sleep_dur = 60 *60*1000;
                    ESP_LOGD("stefan", "sleep_interval is 60min");
                  }
                  else if ( strcmp( id(sleep_interval).state.c_str(), "10min") == 0 ) {
                    sleep_dur = 10 *60*1000;
                    ESP_LOGD("stefan", "sleep_interval is 10min");
                  }
                  else if ( strcmp( id(sleep_interval).state.c_str(), "2min") == 0 ) {
                    sleep_dur = 2 *60*1000;
                    ESP_LOGD("stefan", "sleep_interval is 2min");
                  }
                  else if ( strcmp( id(sleep_interval).state.c_str(), "30s") == 0 ) {
                    sleep_dur = 30 *1000;
                    ESP_LOGD("stefan", "sleep_interval is 30s");
                  }
                  
                  ESP_LOGD("stefan", "debug_gpio turned OFF");
                  id(debug_gpio).turn_off();
                  
                  id(deep_sleep1).allow_deep_sleep();
                  id(deep_sleep1).set_run_duration(0);
                  id(deep_sleep1).set_sleep_duration(sleep_dur);
                  id(deep_sleep1).begin_sleep();
                }
          else:
            - logger.log: "mqtt_done_switch is false!"

# Trick # 2 - allow flag in home assistant to block sleep
#
# Rather than a simple binary though, I opted for a select_helper to give 3 run modes
# - no sleep - 'ota'
# - on the minute - '60s'
# - on the hour - '600s'
# just realized i missed great chance for horrible UI (ota,otm, oth, lol)
text_sensor:

  - platform: mqtt_subscribe
    name: "Candles Sleep Interval"
    id: sleep_interval
    topic: "candles/sleep_interval"
    # internal: true
    disabled_by_default: true
    entity_category: diagnostic
    on_value:
      - globals.set:
          id: mqtt_done_sleep_interval
          value: 'true'
      - logger.log: "candles/sleep_interval: consider_deep_sleep"
      - script.execute: consider_deep_sleep

  - platform: wifi_info
    ip_address:
      name: "WiFi IP"
      icon: mdi:ip-network
      update_interval: 60s
      disabled_by_default: true
      entity_category: diagnostic
      
    ssid:
      name: "WiFi SSID"
      icon: mdi:wifi
      update_interval: 60s
      disabled_by_default: true
      entity_category: diagnostic
    
    mac_address:
      name: "WiFi MAC"
      icon: mdi:identifier
      disabled_by_default: true
      entity_category: diagnostic
    
  - platform: version
    name: "ESPHome Version"
    hide_timestamp: true
    disabled_by_default: true
    entity_category: diagnostic
