substitutions:
  # https://esphome.io/guides/configuration-types.html#substitutions
  dev_name: candle06                  # hostname & entity_id
  dev_friendly_name: Candle 06     # Displayed in HA frontend
  dev_use_address: "${dev_name}.local"
  # dev_icon: mdi:candle

<<: !include .base.yaml
<<: !include .esp32_candlestick.yaml
