substitutions:
  name: kids-lamp-rgb
  friendly_name: Kids Lamp RGB

packages:
  # Bulbs with 1m flash use this package:
  kauf.rgbww: github://KaufHA/kauf-rgbww-bulbs/kauf-bulb.yaml


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  #use_address: "${name}.local"
  #use_address: kauf-bulb-302a08.local # old name

logger:
  baud_rate: 115200
  level: DEBUG

preferences:
  flash_write_interval: 1d 